### ISSUE TITLE
CSS compilation does not work [1h]

### ISSUE THREAD

**Issue by adamhstewart** [Gizra/form-wizard-example#9]
`vendor/consolidation/robo/robo watch:theme-debug`

throws `mkdir: cannot create directory 'web/themes/custom/theme_server/css': File exists`

error repeats in a loop.

Also it's compiling the include statements (literally) instead of including the CSS from those files.

**Comment by amitaibu** [comment]
I've removed Robo in favor of https://github.com/Gizra/form-wizard-example/blob/master/README.md#compile-sass
